"""Add diet, size, lifespan to Species

Revision ID: 0fecb15e852c
Revises: 193377203a96
Create Date: 2026-09-20 12:21:32.917274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fecb15e852c'
down_revision: Union[str, Sequence[str], None] = '193377203a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('diet', sa.String(), nullable=True))
    op.add_column('species', sa.Column('size', sa.String(), nullable=True))
    op.add_column('species', sa.Column('lifespan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'lifespan')
    op.drop_column('species', 'size')
    op.drop_column('species', 'diet')
    # ### end Alembic commands ###
